version: '3.3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PHP-FPM
    volumes:
      - ./:/var/www/html
    networks:
      - app
    depends_on:
      - mysql
      - rabbitmq
    command: bash -c "/var/www/html/docker/scripts/wait-for-db.sh mysql_local root password transfer /bin/true && /var/www/html/docker/scripts/init-app.sh && php-fpm"

  nginx:
    image: nginx:latest
    container_name: NGINX
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    depends_on:
      - php-fpm

  mysql:
    image: mysql:latest
    container_name: MYSQL
    hostname: mysql_local
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: transfer
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RABBITMQ
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log:/var/log/rabbitmq
    restart: always
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app:
    driver: bridge